spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/test
    username: root
    password: mysql

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

PSP:
  toss:
    clientKey: test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com