server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: false
          required-acks: all

        bindings:
          send-out-0:
            producer:
              record-metadata-channel: payment-result

      bindings:
        consume-in-0:
          destination: payment
          group: wallet-service

logging:
  level:
    org:
      springframework:
        transaction: TRACE
        orm:
          jpa: DEBUG
        kafka: TRACE