server:
  port: 8082

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false


  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          auto-create-topics: true
          required-acks: all
          consumer-properties:
            enable.auto.commit: false
            isolation.level: read_committed
          transaction:
            transaction-id-prefix: ledger-
            producer:
              configuration:
                transaction:
                  timeout:
                    ms: 30000

        bindings:
          consume-in-0:
            consumer:
              enable-dlq: true
              dlq-name: payment_ledger_dlq

      bindings:
        consume-in-0:
          destination: payment
          group: ledger-service
          consumer:
            max-attempts: 5

      function:
        definition: consume

logging:
  level:
    org:
      springframework:
        transaction: TRACE
        orm:
          jpa: DEBUG
        kafka: TRACE